// -----------------------------------------------------------------------------
// AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.
// Generated by scripts/gen_register_artifacts.py from scripts/register_map.csv
// -----------------------------------------------------------------------------
module config_registers #(
    parameter int WIDTH = 8
) (
    input  logic                clk,
    input  logic                reset_n,
    input  logic [31:0]         paddr,
    input  logic                psel,
    input  logic                penable,
    input  logic                pwrite,
    input  logic [31:0]         pwdata,
    output logic [31:0]         prdata,
    output logic                pready,
    output logic                pslverr,
    output logic        data_switch_cfg,
    input  logic [WIDTH-1:0]        status_data,
    input  logic        irq_event_set
);

    localparam logic [31:0] CONTROL_ADDR           = 32'h00000000;
    localparam logic [31:0] STATUS_ADDR            = 32'h00000004;
    localparam logic [31:0] GENERIC_CONFIG_ADDR    = 32'h00000008;
    localparam logic [31:0] INTERRUPT_STATUS_ADDR  = 32'h0000000C;

    assign pready  = 1'b1;
    assign pslverr = 1'b0;

    logic [31:0] control_reg;
    logic [31:0] generic_config_reg;
    logic [31:0] interrupt_status_reg;

    assign data_switch_cfg = control_reg[0];

    always_ff @(posedge clk or negedge reset_n) begin
        if (!reset_n) begin
            control_reg <= 32'h00000000;
            generic_config_reg <= 32'h00000000;
            interrupt_status_reg <= 32'h00000000;
        end else begin
            if (psel && penable && pwrite) begin
                unique case (paddr)
                    CONTROL_ADDR: begin
                        control_reg[0] <= pwdata[0];
                    end
                    GENERIC_CONFIG_ADDR: begin
                        generic_config_reg[31:0] <= pwdata[31:0];
                    end
                    INTERRUPT_STATUS_ADDR: begin
                        interrupt_status_reg[0] <= interrupt_status_reg[0] & ~pwdata[0];
                    end
                    default: begin end
                endcase
            end

            // Hardware-set path for W1C fields. HW-set takes priority over SW-clear.
            interrupt_status_reg[0] <= interrupt_status_reg[0] | irq_event_set;
        end
    end

    logic [31:0] control_rd;
    logic [31:0] status_rd;
    logic [31:0] generic_config_rd;
    logic [31:0] interrupt_status_rd;

    always_comb begin
        control_rd = control_reg;

        status_rd = 32'h00000000;
        status_rd[0] = data_switch_cfg;
        for (int i = 0; i < WIDTH; i++) begin
            if ((i + 1) < 32) begin
                status_rd[i + 1] = status_data[i];
            end
        end

        generic_config_rd = generic_config_reg;

        interrupt_status_rd = interrupt_status_reg;

        prdata = '0;
        if (psel && !pwrite) begin
            unique case (paddr)
                CONTROL_ADDR: prdata = control_rd;
                STATUS_ADDR: prdata = status_rd;
                GENERIC_CONFIG_ADDR: prdata = generic_config_rd;
                INTERRUPT_STATUS_ADDR: prdata = interrupt_status_rd;
                default: prdata = '0;
            endcase
        end
    end
endmodule
